config/routes.rb
Bouillabaisse::Application.routes.draw do
  resources :reports

  resources :locations

  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'profile' => 'users#profile'
  get '/confirm/:confirmation_code' => 'users#confirm', :as=>'confirm_user'
  get '/users/:id/confirm' => 'users#confirm_user', :as=>'admin_confirm_user'

  resources :password_resets

  resources :fish

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :role,
                  :send_emails, :is_confirmed, :confirmation_token

  enumerize :role, in: [:demo, :user, :admin, :super_admin]

  attr_accessor :password
  before_save :encrypt_password
  before_create { generate_token(:auth_token) }

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :password_confirmation, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email, :case_sensitive => false
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :role

  ALL_ROLES_ARRAY = [:user, :admin, :super_admin, :demo]
  ASSIGNABLE_ROLES = { admin: [:user, :admin, :demo],
                       super_admin: ALL_ROLES_ARRAY }
  SORTABLE_COLUMNS = [:email, :first_name, :last_name, :created_at, :role, :send_emails,
                      :is_confirmed].collect { |column| column.to_s }
  SORTABLE_STRING_COLUMNS = [:email, :first_name, :last_name].collect { |column| column.to_s }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def send_confirmation
    generate_token(:confirmation_token)
    self.is_confirmed = false
    save!
    UserMailer.account_confirmation(self).deliver
  end
  
  # Returns the full name of the user
  def full_name
    return self.first_name + " " + self.last_name
  end

  # Overrides find_by_email to provide case-insensitive search, useful for logging in.
  def self.find_by_email(email)
    User.where("lower(email) = lower(?)", email).first
  end

  # Finds a single user by its first and last names, using case-insensitive search.
  def self.find_by_names(first_name, last_name)
    User.where("lower(first_name) = lower(?) AND lower(last_name) = lower(?)", 
        first_name, last_name).first
  end

  # returns true if this user is an admin or super-admin
  def is_admin
    return [:admin.to_s, :super_admin.to_s].include?(self.role)
  end

  # returns true if this user is a super-admin
  def is_super_admin
    return self.role == :super_admin.to_s
  end

  # returns the role associated with this user's role string
  def role_type
    return User.role_type_from_string(self.role)
  end

  # returns the role associated with the specified role string
  def self.role_type_from_string(role_string)
    ALL_ROLES_ARRAY.each { |role|
      if role.to_s == role_string
        return role
      end
    }
    return nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @current_user = current_user
    if @current_user.nil?
      redirect_to root_url
      return
    end
  
    # if sort column is a name column, also add other name
    column = sort_column
    order_columns = [wrap_column_if_string(column)]
    if column.ends_with?("name")
      order_columns << wrap_column_if_string(
          column == :first_name.to_s ? :last_name.to_s : :first_name.to_s)
    end

    @users = User.order(get_order_by_string(order_columns, sort_direction))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # wraps the specified column in a "lower()" if it's a string column
  def wrap_column_if_string(column)
    return User::SORTABLE_STRING_COLUMNS.include?(column) ?
       "lower(" + column + ")" : column
  end

  # returns the order_by string for users, using the specified columns and direction
  def get_order_by_string(order_columns, direction)
    order_by_string = ''
    first_column = true
    order_columns.each { |column|
      if first_column
        first_column = false
      else
        order_by_string += ", "
      end
      order_by_string += column + ' ' + direction
    }
    return order_by_string
  end

  # GET /users/new
  # GET /users/new.json
  def new
    logout_user
    @current_user = current_user
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @current_user = current_user
    if @current_user.nil? || !@current_user.is_admin
      redirect_to root_url
      return
    end

    @admin_function = true
  end

  # GET /profile
  def profile
    @admin_function = false
    @current_user = current_user
    @user = @current_user
    if @user.nil?
      redirect_to root_url
    end
  end

  # POST /users
  def create
    @user = User.new(params[:user])

    # new user defaults to "user" role and receiving emails.
    @user.role = :user
    @user.send_emails = true

    if params["commit"]
      begin
        if User.find_by_names(@user.first_name, @user.last_name)
          redirect_to "/sign_up",
              notice: "Error: First/last name is already taken. Please try again."
        elsif @user.save
          # send confirmation email
          @user.send_confirmation
          redirect_to root_url,
              notice: 'User was successfully created; please check your email to confirm account creation!'
        else
          render action: 'new'
        end
      rescue Exception => e
        redirect_to "/sign_up", notice: "Error: Unexpected error occurred: " + e.message
      end
    else
      redirect_to root_url
    end
  end

  # GET /confirm/:confirmation_code
  def confirm
    logout_user
    @user = User.find_by_confirmation_token(params[:confirmation_code])
    notice_message = ""
    if @user
      @user.update_attributes({ is_confirmed: true, confirmation_token: nil })
      notice_message = "Successfully confirmed account; please login!"
    else
      notice_message = "Error: Invalid confirmation URL; token does not exist"
    end
    redirect_to root_url, notice: notice_message
  end

  # GET /users/:id/confirm
  def confirm_user
    @current_user = current_user
    if @current_user.nil? || !@current_user.is_admin
      redirect_to root_url
      return
    end

    user = User.find(params[:id])
    if user && !user.is_confirmed
      user.update_attributes({ is_confirmed: true, confirmation_token: nil })
      confirmation_message = "Successfully confirmed user's account!"
    else
      confirmation_message = "Error: Invalid user for confirmation"
    end
    redirect_to users_url, notice: confirmation_message
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    redirect_url = params.has_key?("admin_fxn") ? ('/users/' + @user.id.to_s + '/edit') : '/profile'

    if params["commit"]
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to redirect_url, notice: 'User successfully updated.' }
          format.json { head :no_content }
        else
          format.html {
            if params.has_key?("admin_fxn")
              @admin_function = true
              @current_user = current_user
              render action: 'edit'
            else
              @admin_function = false
              @current_user = current_user
              render action: 'profile'
            end
          }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to redirect_url
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_hash, :password_salt, :auth_token, :role, :password_reset_token, :password_reset_sent_at, :confirmation_token, :is_confirmed, :send_emails)
    end

    def sort_column
      User::SORTABLE_COLUMNS.include?(params[:sort]) ? params[:sort] : :first_name.to_s
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="span6">
      <fieldset>
        <legend>User Settings</legend>
        <table class="table vertmiddle table-striped table-condensed table-bordered">
          <tr>
            <td><%= f.label :first_name %></td>
            <td><%= f.text_field :first_name, :required => true %></td>
          </tr>
          <tr>
            <td><%= f.label :last_name %></td>
            <td><%= f.text_field :last_name, :required => true %></td>
          </tr>
          <tr>
            <td><%= f.label :email %></td>
            <td><%= f.email_field :email, :required => true %></td>
          </tr>
          <% if @current_user && @admin_function && @current_user.is_admin %>
          <tr>
            <td><%= f.label :role %></td>
            <% if @admin_function && @current_user.is_admin && !@user.is_super_admin %>
              <td class='tdselect'>
                <select name='user[role]'>
                  <% User::ASSIGNABLE_ROLES[@current_user.role_type].each { |role| %>
                    <option value=<%= "'" + role.to_s + "'" %>
                            <%= @user.role == role .to_s ? "selected" : "" %>>
                      <%= role.to_s %>
                    </option>
                  <% } %>
                </select>
              </td>
            <% else %>
              <td><%= @user.role %></td>
            <% end %>
          </tr>
          <% end %>
          <% if @current_user %>
            <tr>
              <td><%= f.label :send_emails, "Send emails" %></td>
              <td><%= f.check_box(:send_emails) %></td>
            </tr>
          <% end %>
        </table>
      </fieldset>
    </div>
    <div class="span6">
      <fieldset>
        <legend>Password Settings</legend>
        <table class="table vertmiddle table-striped table-condensed table-bordered">
          <tr>
            <td><%= f.label :password %></td>
            <td><%= f.password_field :password %></td>
          </tr>
          <tr>
            <td><%= f.label :password_confirmation %></td>
            <td><%= f.password_field :password_confirmation %></td>
          </tr>
        </table>
      </fieldset>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>&nbsp
    <% if @current_user %>
      <input class='btn' name='cancel' type='submit' value='Cancel' />
    <% else %>
      <a href='/' class='btn'>Cancel</a>
    <% end %>
    
    <% if @admin_function == true %>
      <input type=hidden name='admin_fxn' value='' />
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='row-fluid'>
  <div class='span2 center nexttoh1'>
    <a href='/users' class='btn btn-inverse'>All Users</a>
  </div>
  <div class='span8 center'>
    <h3>Edit <%= @user.full_name %>'s profile</h3>
  </div>
  <div class='span2 center nexttoh1'>
    <a href='/users' class='btn btn-inverse'>All Users</a>
  </div>
</div>

<div class='row-fluid'>
  <div class='span12 center'>
    <br/>
    <%= show_notice_as_alert(notice) %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class='row-fluid'>
  <div class='span12 center'>
    <h3>Manage Users</h3>
    <%= show_notice_as_alert(notice) %>

    <table class=<%= "'" + ApplicationHelper::TABLE_CLASS + " smallfonttable'" %>>
      <thead class='rightborderme'><tr>
        <th></th>
        <th><%= sortable :email.to_s %></th>
        <th><%= sortable :first_name.to_s %></th>
        <th><%= sortable :last_name.to_s %></th>
        <th colspan=2><%= sortable :created_at.to_s, "Signup Date" %></th>
        <th><%= sortable(:send_emails.to_s, "Emails") %></th>
        <th><%= sortable :is_confirmed.to_s, "Status" %></th>
        <th colspan=2>Actions</th>
      </tr></thead>

    <% 
      user_count = 0
      @users.each do |user|
      user_count += 1
    %>
      <% if user.is_confirmed %>
        <tr>
      <% else %>
        <tr class='red-row'>
      <% end %>
        <td><%= user_count.to_s %></td>
        <td><%= link_to(user.email, "/users/" + user.id.to_s + "/dashboard") %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.created_at.utc.in_time_zone.strftime("%-m/%-d/%y") %></td>
        <td><%= user.created_at.utc.in_time_zone.strftime("%-I:%M %p") %></td>
        <td><%= image_tag(user.send_emails ? "check.jpg" : "cross.jpg", class: "img_20_20") %></td>
        
        <% if !user.is_confirmed %>
          <td><%= link_to 'Confirm', admin_confirm_user_path(user),
                          data: { confirm: 'Are you sure you want to confirm this user?' } %></td>
        <% else %>
          <td>
            <%= image_tag("check.jpg", class: "img_20_20") %>
          </td>
        <% end %>

        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete,
                        data: { confirm: 'Are you sure you want to delete this user?' } %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class='row-fluid'>
  <div class='span12 center'>
    <h3>Create new account</h3>
  </div>
</div>

<div class='row-fluid'>
  <div class='span12 center'>
    <br/>
    <p><strong>Note: </strong>All fields are required</p>
    
    <%= show_notice_as_alert(notice) %>
    
    <%= render 'form' %>

  </div>
</div>

app/views/users/profile.html.erb
<div class='row-fluid'>
  <div class='span12 center'>
    <h3>Edit <%= @user.full_name %>'s profile</h3>
  </div>
</div>

<div class='row-fluid'>
  <div class='span12 center'>
    <br/>
    <%= show_notice_as_alert(notice) %>
    <%= render 'form' %>
  </div>
</div>