config/routes.rb
Bouillabaisse::Application.routes.draw do
  resources :reports

  resources :locations

  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'profile' => 'users#profile'
  get '/confirm/:confirmation_code' => 'users#confirm', :as=>'confirm_user'
  get '/users/:id/confirm' => 'users#confirm_user', :as=>'admin_confirm_user'

  resources :password_resets

  resources :fish

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :fish
  belongs_to :user
  belongs_to :location

  attr_accessible :photo_url, :length, :weight, :fish_id, :user_id, :location_id
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  def index
    @reports = Report.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @reports }
      format.xml { render xml: @reports }
    end
  end

  # GET /reports/1
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = Report.new(report_params)

    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def report_params
      params.require(:report).permit(:fish_id, :photo_url, :user_id, :length, :weight, :location_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fish_id %><br>
    <%= f.text_field :fish_id %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Fish</th>
      <th>Photo url</th>
      <th>User</th>
      <th>Length</th>
      <th>Weight</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.fish %></td>
        <td><%= report.photo_url %></td>
        <td><%= report.user %></td>
        <td><%= report.length %></td>
        <td><%= report.weight %></td>
        <td><%= report.location %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fish:</strong>
  <%= @report.fish %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @report.photo_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user %>
</p>

<p>
  <strong>Length:</strong>
  <%= @report.length %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @report.weight %>
</p>

<p>
  <strong>Location:</strong>
  <%= @report.location %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>