config/routes.rb
Bouillabaisse::Application.routes.draw do
  resources :reports

  resources :locations

  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'profile' => 'users#profile'
  get '/confirm/:confirmation_code' => 'users#confirm', :as=>'confirm_user'
  get '/users/:id/confirm' => 'users#confirm_user', :as=>'admin_confirm_user'

  resources :password_resets

  resources :fish

end

app/models/fish.rb
class Fish < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  # GET /fish
  def index
    @fish = Fish.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @fish }
      format.xml { render xml: @fish }
    end
  end

  # GET /fish/1
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  def create
    @fish = Fish.new(fish_params)

    if @fish.save
      redirect_to @fish, notice: 'Fish was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /fish/1
  def update
    if @fish.update(fish_params)
      redirect_to @fish, notice: 'Fish was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /fish/1
  def destroy
    @fish.destroy
    redirect_to fish_index_url, notice: 'Fish was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def fish_params
      params.require(:fish).permit(:name)
    end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<h1>Listing fish</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish.each do |fish| %>
      <tr>
        <td><%= fish.name %></td>
        <td><%= link_to 'Show', fish %></td>
        <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
        <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<h1>New fish</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fish.name %>
</p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>